### PR TITLE
Migrate to pathlib

### PR DESCRIPTION
**Pull request by NicoWeio**
This might come down to personal preference, but I feel like using `pathlib` would increase clarity in some places. It also enables us to use some `click` features, like checking for the validity of a provided path.

This PR is a work-in-progress; I just wanted to know if you'd approve this migration.

### CODE REVIEW

**Comment by VxlerieUwU** [comment]
Sure! The existing file handling is really janky and unintuitive, does this mean it could enable users to specify paths that are not inside the data directory?

**Comment by NicoWeio** [comment]
I'm unsure if I understood you correctly, but the answer is probably _yes_. :)
That said, my plan is to keep the current behavior first and improve it afterward.

**Comment by VxlerieUwU** [comment]
> I'm unsure if I understood you correctly, but the answer is probably _yes_. :) That said, my plan is to keep the current behavior first and improve it afterward.

I was saying that Pathlib would enable POSIX paths like ../../primary.jpg to work properly, and also to be able to enter any path on the filesystem.

**Comment by NicoWeio** [comment]
Oh, I just assumed such paths worked already. Anyway, with _pathlib_, they should.

**Comment by VxlerieUwU** [comment]
LGTM, you might want to update your fork to master to solve potential conflicts

**Review by ohld — APPROVED** [review]

**Comment by VxlerieUwU** [comment]
I've fixed all the conflicts, I'll test this and merge it if it works without any problem.

**Comment by NicoWeio** [comment]
I appreciate your effort, but I submitted this as WIP for a reason. You are welcome to continue on this; just know there's definitely some work left to do.

**Pull request closed without merging**
