### PR TITLE
Fix realmoji creation date

### PR DESCRIPTION
**Pull request by Smart123s**
Same as for pictures yesterday. Guess BeReal changed this one as well.

### CODE REVIEW

**Comment by Smart123s** [comment]
Don't merge this yet, please. I forgot something.

**Comment by Smart123s** [comment]
Ok, ready for review & merge. Thanks for your patience.

**Comment by notmarek** [comment]
> Ok, ready for review & merge. Thanks for your patience.

No need to thank me, it's me who should thank you for all your great contributions 👍

**Comment by Smart123s** [comment]
> > Ok, ready for review & merge. Thanks for your patience.
> 
> No need to thank me, it's me who should thank you for all your great contributions 👍

Well, I use the things I contribute myself, so sharing it with the others is no big deal. Also, we should all thank you for starting &  maintaining this awesome project. Our contributions couldn't be possible, if you didn't create this project. Also, you are pretty fast with responding to PRs and issues.

**Pull request merged**
